[versions]
accompanist = "0.37.3"
compose-bom = "2026.01.00"
navigation3 = "1.0.0"
jetbrains-navigation3 = "1.0.0-alpha06"
material3-navigation3 = "1.3.0-alpha06"
jetbrains-material3-navigation3 = "1.3.0-alpha02"
viewmodel-navigation3 = "2.10.0"
jetbrains-viewmodel-navigation3 = "2.10.0-alpha07"
material3 = "1.5.0-alpha12"
jetbrain-material3 = "1.10.0-alpha05"
composeMultiplatform = "1.10.0"
jetbrains-material3-adaptive = "1.3.0-alpha02"
jetbrains-material3-window-size = "1.10.0-alpha05"
material-icons = "1.7.3"
composeHotReload = "1.1.0-alpha03"

[libraries]
bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
foundation = { module = "androidx.compose.foundation:foundation" }
animation = { module = "androidx.compose.animation:animation" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
jetbrains-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
jetbrains-animation = { module = "org.jetbrains.compose.animation:animation", version.ref = "composeMultiplatform" }
jetbrains-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
jetbrains-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
jetbrains-compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }

material3-core = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
material3-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout" }
material3-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation" }
material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3" }
material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }
material-icons-core = { module = "androidx.compose.material:material-icons-core" }
material-icons = { module = "androidx.compose.material:material-icons-extended" }
jetbrains-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "jetbrain-material3" }
jetbrains-material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "jetbrains-material3-adaptive" }
jetbrains-material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "jetbrains-material3-adaptive" }
jetbrains-material3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "jetbrains-material3-adaptive" }
jetbrains-material3-adaptive-navigation-suite = { module = "org.jetbrains.compose.material3:material3-adaptive-navigation-suite", version.ref = "jetbrain-material3" }
jetbrains-material3-window-size = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "jetbrains-material3-window-size" }
jetbrains-material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons" }
jetbrains-material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "material-icons" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
jetbrains-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "jetbrains-navigation3" }

androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3-navigation3" }
jetpack-compose-material3-adaptive-navigation3 = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "jetbrains-material3-navigation3" }

androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "viewmodel-navigation3" }
jetbrains-lifecycle-viewmodel-navigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "jetbrains-viewmodel-navigation3" }

compose-graldePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }

[bundles]
baselibs-android = ["foundation", "animation", "ui", "material-icons", "material3-core", "material3-adaptive", "material3-adaptive-layout", "material3-adaptive-navigation", "material3-adaptive-navigation-suite", "material3-window-size", "material-icons-core"]
baselibs = ["jetbrains-foundation", "jetbrains-animation", "jetbrains-ui", "jetbrains-material3", "jetbrains-material3-adaptive", "jetbrains-material3-adaptive-layout", "jetbrains-material3-adaptive-navigation", "jetbrains-material3-adaptive-navigation-suite", "jetbrains-material3-window-size", "jetbrains-material-icons-core", "jetbrains-material-icons"]
navigation3-android = [
    "androidx-navigation3-runtime", "androidx-navigation3-ui",
    "androidx-material3-adaptive-navigation3",
    "androidx-lifecycle-viewmodel-navigation3"
]
navigation3 = [
    "androidx-navigation3-runtime", "jetbrains-navigation3-ui",
    "jetpack-compose-material3-adaptive-navigation3",
    "jetbrains-lifecycle-viewmodel-navigation3"
]

[plugins]
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
