[versions]
composeWebviewMultiplatform = "2.0.3"
material = "1.13.0"
okio = "3.16.2"
coil3 = "3.3.0"
richtext = "0.20.0"
koin = "4.1.1"
koinAnnotation = "2.3.1"
androidx-test-ext-junit = "1.3.0"
androidx-test-espresso-espresso-core = "3.7.0"
lottie = "6.7.1"
google-services = "4.4.4"
firebase-bom = "34.5.0"
firebase-crashlytics-gradle = "3.0.6"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.4.1"
kermit = "2.0.8"
mmkv = "2.2.4"
mmkv-kotlin = "1.3.1"
desugar = "2.1.5"
kotzilla = "1.3.1"

[libraries]
compose-webview-multiplatform = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "composeWebviewMultiplatform" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }


material = { module = "com.google.android.material:material", version.ref = "material" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

coil3-bom = { module = "io.coil-kt.coil3:coil-bom", version.ref = "coil3" }
coil3-core = { module = "io.coil-kt.coil3:coil-core" }
coil3-gif = { module = "io.coil-kt.coil3:coil-gif" }
coil3-compose = { module = "io.coil-kt.coil3:coil-compose" }
coil3-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3" }

richtext-commonmark = { module = "com.halilibo.compose-richtext:richtext-commonmark", version.ref = "richtext" }
richtext-m3 = { module = "com.halilibo.compose-richtext:richtext-ui-material3", version.ref = "richtext" }

koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koinAnnotation" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koinAnnotation" }

lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso-espresso-core" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }


kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }


mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
mmkv-kotlin = { module = "com.ctrip.flight.mmkv:mmkv-kotlin", version.ref = "mmkv-kotlin" }
kotzilla-sdk-ktor3 = { group = "io.kotzilla", name = "kotzilla-sdk-ktor3", version.ref = "kotzilla" }

[bundles]
koin = ["koin", "koin-compose", "koin-annotations"]
coil3 = ["coil3-core", "coil3-gif", "coil3-compose", "coil3-network-ktor3"]
richtext = ["richtext-commonmark", "richtext-m3"]
lottie = ["lottie", "lottie-compose"]
firebase = ["firebase-analytics", "firebase-crashlytics"]

[plugins]
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
kotzilla = { id = "io.kotzilla.kotzilla-plugin", version.ref = "kotzilla" }
